### ISSUE TITLE
Wishlist: add package selection to <asset />

### ISSUE THREAD

**Issue by johnkeates** [craigburke/client-dependencies-gradle#83]
I was wondering if it is feasible for a gradle plugin to inject a package variable into asset pipeline tags.

Say you have two packages, but both have a 'util.js' file. How would you include those and know which one would win in a GSP?

I think this would be one way to do this: <asset:javascript package="bootstrap" src="util.js" />
This should scope the search path to the bootstrap dir in the vendor dir, thus making sure it only gets files from there.

**Comment by craigburke** [comment]
I think this is more of an asset pipeline question but I can still help you out. In your scenario I'd just use the asset pipeline directives to handle this. 

So you can define a file `app.js` in your `assets/javascripts` folder that looks something like this:
```
//= require /bootstrap/util.js
//= require /foo/util.js
```
Note that the absolute path in the require is **NOT** `/vendor/bootstrap/util.js` because the asset pipeline ignores the first folder in the assets folder when it resolves the path.

Hopefully that helps.

**Comment by johnkeates** [comment]
Yes, that works fine! Thanks.
